#!/bin/bash

#### COLORS #####
# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

#### END COLORS ####

#make disk array
#
disks=( $(lsblk -plno path | grep '/sd.$') )

#lists disks and partitions with numbers
echo -e "Disks list: "
lsblk -nlo path | grep '/sd.$' | less -NF

#Gets user selected disks and makes array
echo -ne "${BWhite}"
read -p "Select partitions to format(feks 1 3) DEFAULT=2 3 4 5: " selecteddisks
echo -ne "${Color_Off}"
selecteddisksarr=($selecteddisks)

if [[ -z "$selecteddisks" ]]; then
        selecteddisksarr=(2 3 4 5)
fi

#debug
#echo ${selecteddisksarr[@]}

#List disks selected using both arrays
for disk in "${selecteddisksarr[@]}"
do
        echo -ne "${BYellow} ${disks[$((disk-1))]} SELECTED\n"
done

echo -ne "\n"
read -p "PRESS ENTER TO START FORMATTING"
echo -ne "\n"

#Format selected disks
for disk in "${selecteddisksarr[@]}"
do
        echo -ne "${BYellow} Formatting Partition. ${Color_Off} \r"
        sudo umount ${disks[$((disk-1))]} &> /dev/null
        echo -ne "${BYellow} Formatting Partition.. ${Color_Off} \r"
        sudo mkfs.vfat -I ${disks[$((disk-1))]} #&> /dev/null
        echo -ne "${BYellow} Formatting Partition... ${Color_Off} \r"
        sync &> /dev/null
done

echo -ne "${BGreen} DONE\a"
