#!/bin/bash

#### Sjekker om fil er oppgitt
#
if [[ -z "$1" ]]; then
	echo "Husk å fyll inn fil sti!"; exit
else
	:
fi

if [[ "$1" != *"png"* ]]; then
	echo "Kan kun printe PNG, monochrome vil ha bedre effekt"; exit
else
	:
fi

#### Sjekker om printer er koblet til og sjekker om man har tilgang
printer=$(lsusb | grep -o QL-1060N)
echo $printer

if [ "$printer" != "QL-1060N" ]; then
	echo "printer er ikke koblet til!"; exit
else
	:
fi

productid=$(lsusb | grep -Po "([a-z0-9]{4}):([a-z0-9]{4})(\w| |,)+($printer)" | grep -Po '([a-z0-9]{4}):\K([a-z0-9]{4})')
mountport=$(sudo dmesg | tail -n 14 | grep -iP "(0x$productid$)" | grep -Po 'lp\d' | head -1)

echo $productid
echo $mountport

access=$(ls -l /dev/usb/$mountport | grep -Po '([crwx]+-){2}\K([rwx-]+)')
if [[ "$access" != *"rw"* ]]; then
	echo -e "Du har ikke tilstrekkelig tilgang til printeren! (/dev/usb/$mountport), trenger rw access for others\nPrøver å sette tilgang.."; sudo chmod o+rw /dev/usb/$mountport
else
	:
fi

#### Progressbar
echo -ne "|          |  0% \r"
sleep 0.1
echo -ne "|#         | 10% \r"
sleep 0.1
echo -ne "|##        | 15% \r"
sleep 0.1
echo -ne "|##        | 20% \r"
sleep 0.1
echo -ne "|###       | 25% \r"
sleep 0.1

#### For å få Q(uality) og a(uto cut) option i qlprint til å fungere må man først printe noe med kun -C(ontinuous) flagget.
#Lager en 1x1 image og printer med -a for å få -QCa til å fungere
#
convert -size 1x1 canvas:white /tmp/white.png
./qlprint/build/qlprint -p /dev/usb/$mountport -C /tmp/white.png #&> /dev/null

#### Mer progressbar
echo -ne "|###       | 30% \r"
sleep 0.1
echo -ne "|####      | 35% \r"
sleep 0.1
echo -ne "|####      | 40% \r"
sleep 0.1
echo -ne "|#####     | 45% \r"
sleep 0.1
echo -ne "|#####     | 50% \r"
sleep 0.1

#### Sender png til utskrift
./qlprint/build/qlprint -p /dev/usb/$mountport -QCa $1 #&> /dev/null

#### Mer progressbar
echo -ne "|######    | 55% \r"
sleep 0.1
echo -ne "|######    | 60% \r"
sleep 0.1
echo -ne "|#######   | 70% \r"
sleep 0.1
echo -ne "|########  | 75% \r"
sleep 0.1
echo -ne "|########  | 80% \r"
sleep 0.1
echo -ne "|######### | 90% \r"
sleep 0.1
echo -ne "|##########| 100%\n\n"
echo "Postlapp skrevet ut!"

###debug
echo $1
