#!/bin/bash

#### COLORS #####
# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

#### END COLORS ####

rm /tmp/politilogg-1.json

radio() {
        curl -sX 'GET' "https://api.politiet.no/politiloggen/v1/messages?Districts=Oslo&Municipalities=Oslo" -H 'accept: text/plain' -o /tmp/politilogg.json
}

json_file="/tmp/politilogg.json"
previous_data="/tmp/politilogg-1.json" # Temporary file to store previous data

check_file() {
# Create the temporary file if it doesn't exist
if [ ! -f "$previous_data" ]; then
        echo "[]." > $previous_data
fi
}

# Function to check for new threads and messages
check_for_updates() {

  # Check if data field exists and is not null
  current_data=$(jq -c '.data // [] | .[] | {threadId, id, createdOn, text}' "$json_file")

  # Compare the current data with the previously stored data
  new_entries=$(comm -13 <(jq -c '.[]' "$previous_data" | sort) <(echo "$current_data" | sort))

  if [ -n "$new_entries" ]; then
    # Loop through each new entry and print the output
    echo "$new_entries" | jq -c '. | {threadId, id, createdOn, text}' | while IFS= read -r entry; do
      threadId=$(echo "$entry" | jq -r '.threadId')
      id=$(echo "$entry" | jq -r '.id | sub("'"$threadId"'-"; "")')
      createdOn=$(echo "$entry" | jq -r '.createdOn')
      text=$(echo "$entry" | jq -r '.text')

      # Format the createdOn date using the 'date' command
      formatted_date=$(date -d "$createdOn" +"%H:%M %d-%m-%y")
      echo -e "${Color_Off}"
      echo -e "ID:${BYellow} ${threadId}${Color_Off}-${id}"
      echo -e "Dato: $formatted_date"
      echo -e "${BWhite}Melding:\n$text"
      echo -e "${Black}----------------------------------------"
      echo -e "${Color_Off}"
   done

    # Update the previous data with the current data
    echo "$current_data" | jq -s '.' > "$previous_data"
    echo -e "\a"
  fi
}

# Continuously check for updates every 5 seconds
while true; do
  radio
  check_file
  check_for_updates
  sleep 300
done
