#!/bin/bash

#### Sjekker om printer er koblet til og sjekker om man har tilgang

printer=$(lsusb | grep -o QL-570)
echo $printer

if [ "$printer" != "QL-570" ]; then
	echo "printer er ikke koblet til!"; exit
else
	:
fi

productid=$(lsusb | grep -Po "([a-z0-9]{4}):([a-z0-9]{4})(\w| |,)+($printer)" | grep -Po '([a-z0-9]{4}):\K([a-z0-9]{4})')
mountport=$(sudo dmesg | tail -n 14 | grep -iP "(0x$productid$)" | grep -Po 'lp\d' | head -1)

echo $productid
echo $mountport

access=$(ls -l /dev/usb/$mountport | grep -Po '([crwx]+-){2}\K([rwx-]+)')
if [[ "$access" != *"rw"* ]]; then
	echo -e "Du har ikke tilstrekkelig tilgang til printeren! (/dev/usb/$mountport), trenger rw access for others\nPrøver å sette tilgang.."; sudo chmod o+rw /dev/usb/$mountport
else
	:
fi

#### Henter variables for imagemagick bildet
read -p "Navn på skole: " skolenavn
read -p "Adresse til skole: " adresse

#### Henter variable og tester om Poststed er riktig format.
read -p "Poststed (feks 1234 OSLO): " poststed

#### legger til next line slik at imagemagick deler opp output
skolenavn+=" \n "
adresse+=" \n "

#### Progressbar
echo -ne "|          |  0% \r"
sleep 0.1

echo -ne "|#         | 10% \r"
sleep 0.1

echo -ne "|##        | 15% \r"
sleep 0.1

echo -ne "|##        | 20% \r"
sleep 0.1

echo -ne "|###       | 25% \r"
sleep 0.1



#### Lager en png med info
convert -background white -fill black -size 600x200 -gravity South label:"$skolenavn$adresse$poststed" -border 60x68 -monochrome -rotate 90 /tmp/postlapp.png

#### Mer progressbar
echo -ne "|###       | 30% \r"
sleep 0.1

echo -ne "|####      | 35% \r"
sleep 0.1

echo -ne "|####      | 40% \r"
sleep 0.1

echo -ne "|#####     | 45% \r"
sleep 0.1

echo -ne "|#####     | 50% \r"
sleep 0.1

#### Sender png til utskrift
cd ~/ql570 ;./ql570 /dev/usb/$mountport 62x29 /tmp/postlapp.png &> /dev/null

#### Mer progressbar
echo -ne "|######    | 55% \r"
sleep 0.1

echo -ne "|######    | 60% \r"
sleep 0.1

echo -ne "|#######   | 70% \r"
sleep 0.1

echo -ne "|########  | 75% \r"
sleep 0.1

echo -ne "|########  | 80% \r"
sleep 0.1

echo -ne "|######### | 90% \r"
sleep 0.1

echo -ne "|##########| 100%\n\n"
echo "Postlapp skrevet ut!"

rm /tmp/postlapp.png
