#!/bin/bash

link=$1
link+='.json'

curl --user-agent 'bobby' $link -o /tmp/reddit

videolink=$(grep -P -o '(https).*?(\d\d\d.mp4)' /tmp/reddit | head -1)

ffmpeg -i $videolink -hide_banner -loglevel error -y -c copy ~/Videos/videofromreddit.mp4 && echo "Video lastet ned"

rm /tmp/reddit

