#!/bin/bash

### Grab website
url=$1

### Grab Video link
video=$(curl -L "$url" -s | grep -Pom 1 '(mp4\"\:\")\K(https:\/\/[a-z-\.\/0-9\_]+)(\.mp4)')

### Play video with link
mpv $video

### Debug
#echo $1
#echo $url
#echo $video
