#!/bin/bash

curl $1 -so /tmp/vgtv

video=$(grep -P -o '(https...dd).*?mp4' /tmp/vgtv | head -1)

rm /tmp/vgtv

ffmpeg -hide_banner -loglevel error -y -i $video -c copy ~/Videos/vgtv.mp4 && echo "Video lastet ned"

